Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,16 +17,18 @@ jobs:
       run: |
         echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
 
-    - name: Build Docker image and push to Heroku
+    - name: Debug Docker Build
       run: |
-        docker build -t registry.heroku.com/finalapp2/web .
-        docker push registry.heroku.com/finalapp2/web
+        docker build -t registry.heroku.com/finalapp2/web . && echo "Build successful" || echo "Build failed"
+
+    - name: Push Docker image to Heroku
+      run: docker push registry.heroku.com/finalapp2/web
 
     - name: Install Heroku CLI
       run: |
         curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
 
     - name: Release Docker image on Heroku
-      run: heroku container:release web --app finalapp2
       env:
         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+      run: heroku container:release web --app finalapp2
